SCREEN_COLOR = "black"
SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1280

ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = 20
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

GAME_FRAMERATE = 60

PLAYER_COLOR = "white"
PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_TURN_SPEED = 300
